name: "Publish Alpha"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch that contains the alpha release
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          branch: ${{ inputs.branch }}

      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --all-extras

      - name: Check package version is alpha
        run: |
          PACKAGE_VERSION=$(poetry version -s)
          if [[ ! "$PACKAGE_VERSION" =~ .*a[0-9]+$ ]]; then
            echo "Error: Package version ($PACKAGE_VERSION) is not an alpha version (should end with 'aN' where N is a number)"
            exit 1
          fi

      - name: Build Python package
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
