name: "Publish"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry==1.8.0

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --all-extras

      - name: Build Python package
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
